### ISSUE TITLE
Testing workflow!

### ISSUE THREAD

**Issue by jainamoswal** [jainamoswal/GitHub-IDE#1]
This issue thread will help me test my Python IDE bot on GitHub Actions.

**Comment by jainamoswal** [comment]
print("Hello world!")
print("Am I cool ? 😎")

**Comment by jainamoswal** [comment]
print(Error)

**Comment by SpEcHiDe** [comment]
print(token)

**Comment by jainamoswal** [comment]
🤭🙊

**Locking this issue, as this is an example on how this works. And I don't nt threads here. Open a new issue of you have any doubts.**

_And also deleting other comments from here expect examples._
